name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Install Snapcraft (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: sudo snap install snapcraft --classic

      - name: Build app
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            npx electron-builder --mac
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            npx electron-builder --linux
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            npx electron-builder --win
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-artifacts
          path: dist/
