name: Build and Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: |
          npm install
          npm install undici@5.28.2 --save-exact

      - name: Package application
        run: npm run package
      
      - name: Build and publish (Universal Mac)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx electron-builder --config ./build-config.js --mac --arm64 --publish always

  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: |
          npm install
          npm install undici@5.28.2 --save-exact

      - name: Package application
        run: npm run package
      
      - name: Build and publish (Linux)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx electron-builder --config ./build-config.js --linux --x64 --arm64 --publish always

  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: |
          npm install
          npm install undici@5.28.2 --save-exact

      - name: Package application
        run: npm run package
      
      - name: Build and publish (Windows)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx electron-builder --config ./build-config.js --win --x64 --arm64 --publish always

  build-intel-macos:
    runs-on: macos-13
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: |
          npm install
          npm install undici@5.28.2 --save-exact

      - name: Package application
        run: npm run package
      
      - name: Build and publish (Intel Mac)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx electron-builder --config ./build-config.js --mac --x64 --publish always